version: '2.2'
services:
  backend:
    image: augustinaloys/backend-app
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80
    scale: 50
  lb:
    image: dockercloud/haproxy
    links:
      - backend
    ports: 
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - backend
